spring:
  sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 8081

